### ISSUE TITLE
ImageSpan 图标丢失情况

### ISSUE THREAD

**Issue by Thomsen** [bytedance/RealRichText#3]
一个列表中有多个RealRichText，含有图片。
![image](https://user-images.githubusercontent.com/963095/49846711-8dadbd80-fe07-11e8-8c9c-e28c8c3ef6de.png)

列表滑动到底部，RealRichText处于不可见，当再次可见时，图标消失，
![image](https://user-images.githubusercontent.com/963095/49846721-9bfbd980-fe07-11e8-8c46-c8c1eac3be61.png)

麻烦看下什么问题 ？

**Comment by limengyun2008** [comment]
麻烦贴一下你的源代码，我这边debug看一下。

**Comment by Thomsen** [comment]
> 麻烦贴一下你的源代码，我这边debug看一下。

可以通过
https://github.com/Thomsen/RealRichText/tree/master/example  

调试看看

**Comment by limengyun2008** [comment]
> > 麻烦贴一下你的源代码，我这边debug看一下。
> 
> 可以通过
> https://github.com/Thomsen/RealRichText/tree/master/example
> 
> 调试看看

不好意思，昨天忙，今天解决了。你拉下代码试试。感谢反馈

**Comment by Thomsen** [comment]
问题已经解决，谢谢！
