### ISSUE TITLE
一直调用paint方法会不会消耗资源

### ISSUE THREAD

**Issue by SpikeYeh** [bytedance/RealRichText#4]
我看到控制台会一直打印paint里面的日志，是一直在打印 那应该是一直在调用，那这个会不会消耗资源呢？

**Comment by limengyun2008** [comment]
这个跟我没什么关系。。。不仅仅是我的paint被调用了，你界面所有地方都在调用paint。 应该是你的某个地方的动画导致触发了全局重绘，检查一下你的界面，把一直动的地方用RepaintBoundary包一层就可以解决这个问题。
