### ISSUE TITLE
有扩展编辑框使支持类似富文本的计划吗？

### ISSUE THREAD

**Issue by hyz1992** [bytedance/RealRichText#7]
我有个项目，要求输入框编辑内容的时候，也支持表情图片、@、话题。@和话题我勉强能做，不过支持图片比较难，没什么头绪。你这个富文本图片的实现方法，不知是否有可能移植到编辑框里面？

**Comment by limengyun2008** [comment]
暂时没研究过，不过官方有个issue是要改进的  你可以看看 https://github.com/flutter/flutter/issues/2022

**Comment by hyz1992** [comment]
我参照你的real_rich_text，完成了输入框对图片表情的支持：
[rich_textfield](https://github.com/hyz1992/rich_textfield.git)
